- hosts: docker

  tasks:

  - name: upgrade all packages
    yum: name=* state=latest
    
    
  - name: libselinux-python install
    yum: name=libselinux-python
         state=present

  - name: Disable selinux
    selinux: state=disabled

  - name: Add Docker Yum repo
    copy: src=docker.repo
          dest=/etc/yum.repos.d/
          owner=root group=root mode=0644

  - name: docker-engine install
    yum: name=docker-engine
         state=present

  - name: Docker Service Start
    service: name=docker
             state=started
             enabled=yes

  - name: Add Consul SystemD Service 
    copy: src=consul.service
          dest=/usr/lib/systemd/system/
          owner=root group=root mode=0644
          
  - name: Add Registrator SystemD Service 
    copy: src=registrator.service
          dest=/usr/lib/systemd/system/
          owner=root group=root mode=0644          

  - name: Add DockerUI SystemD Service 
    copy: src=dockerui.service
          dest=/usr/lib/systemd/system/
          owner=root group=root mode=0644  

  - name: Reload SystemD
    command: /bin/systemctl daemon-reload
  

  - name: Consul Service Start
    service: name=consul
             state=started
             enabled=yes

  - name: Registrator Service Start
    service: name=registrator
             state=started
             enabled=yes
             
  - name: DockerUI Service Start
    service: name=dockerui
             state=started
             enabled=yes
