- hosts: docker

  tasks:

  - name: upgrade all packages
    yum: name=* state=latest
    
    
  - name: libselinux-python install
    yum: name=libselinux-python
         state=present

  - name: Disable selinux
    selinux: state=disabled

  - name: Add Docker Yum repo
    copy: src=docker.repo
          dest=/etc/yum.repos.d/
          owner=root group=root mode=0644

  - name: docker-engine install
    yum: name=docker-engine
         state=present

  - name: Docker Service Start
    service: name=docker
             state=started
             enabled=yes

  - name: Add Consul SystemD Service 
    copy: src=consul.service
          dest=/usr/lib/systemd/system/
          owner=root group=root mode=0644
    notify:
    - reload systemd

  - name: Consul Service Start
    service: name=consul
             state=started
             enabled=yes
